name: Build package
on:
  workflow_dispatch:
    inputs:
      package:
        description: "Package to build"
        required: true
        type: string
      version:
        description: "Version to build"
        required: true
        type: string
jobs:
  gpg:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Init Hermit
        run: ./bin/hermit env --raw >> $GITHUB_ENV
      - name: Build
        run: make VERSION=${{ inputs.version }} -C pkgs/${{ inputs.package }}
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.package }}-${{ inputs.version }}
          allowUpdates: true
          artifacts: "pkgs/${{ inputs.package }}/${{ inputs.package }}-${{ inputs.version }}-*.tar.xz"
          token: ${{ secrets.GITHUB_TOKEN }}
